=== youngmonkeys/ezyfox-server/ezyfox-server-core/test-data/settings/zones/ezy-zone-settings-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tvd12.com/schema/ezyfox/settings"
           xmlns="http://www.tvd12.com/schema/ezyfox/settings" elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="settings">
        <xs:complexType>
            <xs:all>
                <xs:element ref="max-users" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="applications" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="plugins" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="user-management" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="max-users" type="xs:integer"/>
    <xs:element name="applications" type="applications-type"/>
    <xs:element name="application" type="application-type"/>
    <xs:element name="plugins" type="plugins-type"/>
    <xs:element name="plugin" type="plugin-type"/>
    <xs:element name="user-management" type="user-management-type"/>

    <xs:complexType name="plugins-type">
        <xs:all>
            <xs:element ref="plugin" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="plugin-type">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="entry-loader" type="class-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="priority" type="xs:integer" default="0" minOccurs="0" maxOccurs="1"/>
            <xs:element name="thread-pool-size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="config-file" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
            <xs:element name="listen-events" type="plugin-listen-events" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="plugin-listen-events">
        <xs:sequence>
            <xs:element name="event" type="plugin-listen-event-type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="plugin-listen-event-type">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="USER_LOGIN"/>
                    <xs:enumeration value="USER_ADDED"/>
                    <xs:enumeration value="USER_REMOVED"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>

    <xs:complexType name="applications-type">
        <xs:all>
            <xs:element ref="application" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="application-type">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="entry-loader" type="class-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="max-users" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="thread-pool-size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="config-file" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="administrators-type">
        <xs:sequence>
            <xs:element name="administrator" type="administrator-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="administrator-type">
        <xs:all>
            <xs:element name="username" type="not-empty-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="password" type="not-empty-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="api-access-token" type="not-empty-type" minOccurs="1" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="user-management-type">
        <xs:all>
            <xs:element name="allow-guest-login" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="guest-name-prefix" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="user-max-idle-time" type="xs:long" minOccurs="0" maxOccurs="1"/>
            <xs:element name="user-name-pattern" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="max-session-per-user" type="xs:int" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="class-type">
        <xs:restriction base="not-empty-type"/>
    </xs:simpleType>

    <xs:simpleType name="file-type">
        <xs:restriction base="not-empty-type"/>
    </xs:simpleType>

    <xs:simpleType name="not-empty-type">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== youngmonkeys/ezyfox-server/ezyfox-server-core/test-data/settings/zones/ezy-zone-settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings
    xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
          ezy-zone-settings-1.0.0.xsd"
    xmlns="http://www.tvd12.com/schema/ezyfox/settings"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <max-users>10000</max-users>

    <user-management>
        <allow-guest-login>true</allow-guest-login>
        <guest-name-prefix>Guest#</guest-name-prefix>
        <user-max-idle-time>15000</user-max-idle-time>
        <max-session-per-user>15</max-session-per-user>
        <user-name-pattern>^[a-z0-9_.]{3,36}$</user-name-pattern>
    </user-management>

    <applications>
        <application>
            <name>ezyfox-chat</name>
            <entry-loader>com.tvd12.ezyfoxserver.chat.EzyChatEntryLoader</entry-loader>
            <max-users>10000</max-users>
            <thread-pool-size>30</thread-pool-size>
            <config-file>config.properties</config-file>
        </application>
    </applications>

    <plugins>
        <plugin>
            <name>ezyfox-auth-plugin</name>
            <priority>-1</priority>
            <entry-loader>com.tvd12.ezyfoxserver.plugin.auth.EzyAuthPluginEntryLoader</entry-loader>
            <thread-pool-size>30</thread-pool-size>
            <config-file>config.properties</config-file>
            <listen-events>
                <event>USER_LOGIN</event>
                <event>USER_ADDED</event>
                <event>USER_REMOVED</event>
            </listen-events>
        </plugin>
    </plugins>
</settings>

<!-- http://localhost:8080/schema/ezyfox/settings/ -->
