=== youngmonkeys/ezyfox-server/ezyfox-server-core/src/main/resources/ezy-settings-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tvd12.com/schema/ezyfox/settings"
           xmlns="http://www.tvd12.com/schema/ezyfox/settings" elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="settings">
        <xs:complexType>
            <xs:all>
                <xs:element ref="debug" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="node-name" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="max-sessions" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="thread-pool-size" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="streaming" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="http" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="socket" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="udp" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="web-socket" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="administrators" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="session-management" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="event-controllers" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="zones" minOccurs="0" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="debug" type="xs:boolean"/>
    <xs:element name="node-name" type="xs:string"/>
    <xs:element name="max-sessions" type="xs:integer"/>
    <xs:element name="http" type="http-type"/>
    <xs:element name="socket" type="socket-type"/>
    <xs:element name="udp" type="udp-type"/>
    <xs:element name="web-socket" type="web-socket-type"/>
    <xs:element name="streaming" type="streaming-type"/>
    <xs:element name="thread-pool-size" type="thread-pool-size-type"/>
    <xs:element name="administrators" type="administrators-type"/>
    <xs:element name="session-management" type="session-management-type"/>
    <xs:element name="event-controllers" type="event-controllers-type"/>
    <xs:element name="event-controller" type="event-controller-type"/>
    <xs:element name="zone" type="zone-type"/>
    <xs:element name="zones" type="zones-type"/>

    <xs:complexType name="thread-pool-size-type">
        <xs:all>
            <xs:element name="statistics" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="stream-handler" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="socket-data-receiver" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="system-request-handler" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="extension-request-handler" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="socket-disconnection-handler" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="socket-user-removal-handler" type="xs:integer" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="streaming-type">
        <xs:all>
            <xs:element name="enable" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="socket-type">
        <xs:all>
            <xs:element name="port" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="address" type="not-empty-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-type" type="ssl-type-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-handshake-timeout" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="codec-creator" type="codec-creator-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="max-request-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="tcp-no-delay" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="writer-thread-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="udp-type">
        <xs:all>
            <xs:element name="port" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="address" type="not-empty-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="max-request-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="channel-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="handler-thread-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="web-socket-type">
        <xs:all>
            <xs:element name="port" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="address" type="not-empty-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-port" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="ssl-config" type="ssl-config-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="codec-creator" type="codec-creator-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="max-frame-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="min-handler-thread-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="max-handler-thread-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="writer-thread-pool-size" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="management-enable" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="ssl-type-type">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="CERTIFICATION"/>
                    <xs:enumeration value="CUSTOMIZATION"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>

    <xs:complexType name="ssl-config-type">
        <xs:all>
            <xs:element name="file" type="file-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="loader" type="class-type" maxOccurs="1" minOccurs="0"/>
            <xs:element name="context-factory-builder" type="class-type" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="http-type">
        <xs:all>
            <xs:element name="port" type="xs:integer" maxOccurs="1" minOccurs="0"/>
            <xs:element name="active" type="xs:boolean" maxOccurs="1" minOccurs="0"/>
            <xs:element name="max-threads" type="xs:integer" maxOccurs="1" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="administrators-type">
        <xs:sequence>
            <xs:element name="administrator" type="administrator-type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="administrator-type">
        <xs:all>
            <xs:element name="username" type="not-empty-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="password" type="not-empty-type" minOccurs="1" maxOccurs="1"/>
            <xs:element name="access-token" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="session-management-type">
        <xs:all>
            <xs:element name="session-max-idle-time" type="xs:long" minOccurs="0" maxOccurs="1"/>
            <xs:element name="session-max-waiting-time" type="xs:long" minOccurs="0" maxOccurs="1"/>
            <xs:element name="session-max-request-per-second" type="session-max-request-per-second-type" minOccurs="0"
                        maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="session-max-request-per-second-type">
        <xs:all>
            <xs:element name="value" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="action" type="session-max-request-per-second-action-type"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="session-max-request-per-second-action-type">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="DROP_REQUEST"/>
                    <xs:enumeration value="DISCONNECT_SESSION"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>

    <xs:complexType name="event-controllers-type">
        <xs:all>
            <xs:element ref="event-controller"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="event-controller-type">
        <xs:all>
            <xs:element name="event-type" type="listen-event-type" maxOccurs="1" minOccurs="1"/>
            <xs:element name="controller" type="class-type" maxOccurs="1" minOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="listen-event-type">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="SERVER_INITIALIZING"/>
                    <xs:enumeration value="SERVER_READY"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>

    <xs:complexType name="zones-type">
        <xs:all>
            <xs:element ref="zone" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="zone-type">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="config-file" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
            <xs:element name="active" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="codec-creator-type">
        <xs:restriction base="class-type"/>
    </xs:simpleType>

    <xs:simpleType name="class-type">
        <xs:restriction base="not-empty-type"/>
    </xs:simpleType>

    <xs:simpleType name="file-type">
        <xs:restriction base="not-empty-type"/>
    </xs:simpleType>

    <xs:simpleType name="not-empty-type">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== youngmonkeys/ezyfox-server/ezyfox-server-core/src/test/resources/ezy-settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings
    xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
          ezy-settings-1.0.0.xsd"
    xmlns="http://www.tvd12.com/schema/ezyfox/settings"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <node-name>localhost</node-name>
    <max-sessions>30000</max-sessions>

    <streaming>
        <enable>true</enable>
    </streaming>

    <socket>
        <port>3005</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <max-request-size>65536</max-request-size>
        <codec-creator>com.tvd12.ezyfoxserver.netty.codec.MsgPackCodecCreator</codec-creator>
    </socket>

    <web-socket>
        <port>2208</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <ssl-port>2812</ssl-port>
        <max-frame-size>65536</max-frame-size>
        <ssl-active>false</ssl-active>
        <ssl-config>
            <file>ssl-config.properties</file>
            <loader>com.tvd12.ezyfoxserver.ssl.EzySimpleSslConfigLoader</loader>
            <context-factory-builder>com.tvd12.ezyfoxserver.ssl.EzySimpleSslContextFactoryBuilder</context-factory-builder>
        </ssl-config>
        <codec-creator>com.tvd12.ezyfoxserver.netty.codec.JacksonWsCodecCreator</codec-creator>
    </web-socket>

    <administrators>
        <administrator>
            <username>admin</username>
            <password>admin</password>
            <api-access-token>admin</api-access-token>
        </administrator>
    </administrators>

    <session-management>
        <session-max-idle-time>15000</session-max-idle-time>
        <session-max-waiting-time>30000</session-max-waiting-time>
        <session-max-request-per-second>
            <value>20</value>
            <action>DISCONNECT_SESSION</action>
        </session-max-request-per-second>
    </session-management>

    <event-controllers>
        <event-controller>
            <event-type>SERVER_READY</event-type>
            <controller>com.tvd12.ezyfoxserver.handler.ServerReadyHandler</controller>
        </event-controller>
    </event-controllers>

    <zones>
        <zone>
            <name>example</name>
            <config-file>ezy-zone-settings.xml</config-file>
            <active>true</active>
        </zone>
    </zones>

</settings>

<!-- http://localhost:8080/schema/ezyfox/settings/ -->

=== youngmonkeys/ezyfox-server/ezyfox-server-core/src/main/resources/ezy-settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
          ezy-settings-1.0.0.xsd"
        xmlns="http://www.tvd12.com/schema/ezyfox/settings">

    <node-name>localhost</node-name>
    <max-sessions>30000</max-sessions>

    <thread-pool-size>
        <statistics>1</statistics>
        <stream-handler>8</stream-handler>
        <socket-data-receiver>8</socket-data-receiver>
        <system-request-handler>8</system-request-handler>
        <extension-request-handler>8</extension-request-handler>
        <socket-disconnection-handler>2</socket-disconnection-handler>
        <socket-user-removal-handler>3</socket-user-removal-handler>
    </thread-pool-size>

    <streaming>
        <enable>true</enable>
    </streaming>

    <socket>
        <port>3005</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <ssl-active>true</ssl-active>
        <ssl-type>CUSTOMIZATION</ssl-type>
        <ssl-handshake-timeout>300</ssl-handshake-timeout>
        <tcp-no-delay>true</tcp-no-delay>
        <max-request-size>4096</max-request-size>
        <writer-thread-pool-size>8</writer-thread-pool-size>
        <codec-creator>com.tvd12.ezyfox.codec.MsgPackCodecCreator</codec-creator>
    </socket>

    <udp>
        <port>2611</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <max-request-size>1024</max-request-size>
        <channel-pool-size>8</channel-pool-size>
        <handler-thread-pool-size>5</handler-thread-pool-size>
    </udp>

    <web-socket>
        <port>2208</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <ssl-port>2812</ssl-port>
        <max-frame-size>2048</max-frame-size>
        <min-handler-thread-pool-size>4</min-handler-thread-pool-size>
        <max-handler-thread-pool-size>16</max-handler-thread-pool-size>
        <writer-thread-pool-size>8</writer-thread-pool-size>
        <management-enable>true</management-enable>
        <ssl-active>false</ssl-active>
        <ssl-config>
            <file>ssl-config.properties</file>
            <loader>com.tvd12.ezyfoxserver.ssl.EzySimpleSslConfigLoader</loader>
            <context-factory-builder>com.tvd12.ezyfoxserver.ssl.EzySimpleSslContextFactoryBuilder</context-factory-builder>
        </ssl-config>
        <codec-creator>com.tvd12.ezyfox.codec.JacksonCodecCreator</codec-creator>
    </web-socket>

    <administrators>
        <administrator>
            <username>admin</username>
            <password>admin</password>
            <access-token>admin</access-token>
        </administrator>
    </administrators>

    <session-management>
        <session-max-idle-time>60</session-max-idle-time>
        <session-max-waiting-time>15</session-max-waiting-time>
        <session-max-request-per-second>
            <value>20</value>
            <action>DISCONNECT_SESSION</action>
        </session-max-request-per-second>
    </session-management>

    <event-controllers>
        <event-controller>
            <event-type>SERVER_READY</event-type>
            <controller>com.tvd12.ezyfoxserver.handler.ServerReadyHandler</controller>
        </event-controller>
    </event-controllers>

    <zones>
        <zone>
            <name>example</name>
            <config-file>ezy-zone-settings.xml</config-file>
            <active>true</active>
        </zone>
    </zones>

</settings>

<!-- http://localhost:8080/schema/ezyfox/settings/ -->

=== youngmonkeys/ezyfox-server/ezyfox-server-core/test-data/settings/ezy-settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings
    xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
          ezy-settings-1.0.0.xsd"
    xmlns="http://www.tvd12.com/schema/ezyfox/settings"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <max-sessions>30000</max-sessions>

    <socket>
        <port>3005</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <max-request-size>65536</max-request-size>
        <codec-creator>com.tvd12.ezyfoxserver.netty.codec.MsgPackCodecCreator</codec-creator>
    </socket>

    <web-socket>
        <port>2208</port>
        <address>0.0.0.0</address>
        <active>true</active>
        <ssl-port>2812</ssl-port>
        <max-frame-size>65536</max-frame-size>
        <ssl-active>false</ssl-active>
        <ssl-config>
            <file>ssl-config.properties</file>
            <loader>com.tvd12.ezyfoxserver.ssl.EzySimpleSslConfigLoader</loader>
            <context-factory-builder>com.tvd12.ezyfoxserver.ssl.EzySimpleSslContextFactoryBuilder</context-factory-builder>
        </ssl-config>
        <codec-creator>com.tvd12.ezyfoxserver.netty.codec.JacksonWsCodecCreator</codec-creator>
    </web-socket>

    <administrators>
        <administrator>
            <username>admin</username>
            <password>admin</password>
            <api-access-token>admin</api-access-token>
        </administrator>
    </administrators>

    <session-management>
        <session-allow-reconnect>true</session-allow-reconnect>
        <session-max-idle-time>15000</session-max-idle-time>
        <session-max-waiting-time>30000</session-max-waiting-time>
        <session-max-request-per-second>
            <value>20</value>
            <action>DISCONNECT_SESSION</action>
        </session-max-request-per-second>
    </session-management>

    <zones>
        <zone>
            <name>example</name>
            <config-file>ezy-zone-settings.xml</config-file>
            <active>true</active>
        </zone>
        <zone>
            <name>example2</name>
            <config-file>ezy-zone-settings.xml</config-file>
            <active>false</active>
        </zone>
    </zones>

</settings>

<!-- http://localhost:8080/schema/ezyfox/settings/ -->
